disabled_rules: # rule identifiers to exclude from running
- cyclomatic_complexity
- line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Project Setup Fastlane UITests
- Tests
- Project SetupTests
